mimamorukun/mimamorukun/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('status/', include('status.urls')),
    path('admin/', admin.site.urls),
]

mimamorukun/status/urls.py
from django.urls import path

from . import views

app_name = 'status' 

urlpatterns = [
    path('', views.login, name='login'),
    path('index/', views.index, name='index'),
    path('update/<int:member_pk>', views.upd, name='update'),
]

mimamorukun/status/models.py
from django.db import models
from django.utils import timezone
# Create your models here.


class Member(models.Model):
    PLACE_CHOICE = (
        ('HOME', '在宅'),
        ('MEJIRO', '目白台'),
        ('OOTE', '大手町'),
        ('DAYOFF','休暇'),
    )

    STATUS_CHOICE = (
        ('WORK', '勤務中'),
        ('LEAVE', '離席中'),
        ('LUNCH', '食事中'),
    )

    name = models.CharField(
        verbose_name='名前',
        max_length=200,
    )

    place = models.CharField(
        verbose_name='勤務場所',
        choices=PLACE_CHOICE,
        max_length=10,
        default='目白台',
    )

    status = models.CharField(
        verbose_name='勤務ステータス',
        choices=STATUS_CHOICE,
        max_length=10,
        default='勤務中',
    )

    #********************************************
    status_work = models.BooleanField(
        default=False,
    )

    status_home = models.BooleanField(
        default=False,
    )

    status_meeting = models.BooleanField(
        default=False,
    )

    status_lunch = models.BooleanField(
        default=False,
    )

    last_update_time = models.DateTimeField(
        default=timezone.now
    )

    def __str__(self):
        return self.name

mimamorukun/status/views.py
from django.shortcuts import render, redirect
from django.http import HttpResponse
from .models import Member
from django.utils import timezone

#ログインユーザーのプライマリーキー 　グローバル変数として宣言するとどのメソッドでも共通して使える。
global user_pk
global pos_y


#ログイン画面
def login(request):
    global user_pk
    global pos_y
  
    #POSTメソッド＝ログイン画面でloginボタンを押したとき
    if request.method == "POST":
        username = request.POST['username']

        #ユーザーが存在する場合
        try:
            user = Member.objects.get(name=username)
            user_pk = user.pk
            pos_y = 0
            return redirect('status:index')
          
        #ユーザーが存在しない場合
        except:
            return render(request, 'status/login.html', {'error':'ユーザーが見つかりません'})  
        
    #GETメソッド＝ログイン画面が呼び出されるとき
    return render(request, 'status/login.html')


#ホーム画面呼び出し
def index(request):
    global pos_y
    member = Member.objects.order_by('id')
    return render(request, 'status/index.html', {'member': member,'position':pos_y})


#ステータス更新    (member_pkにはindex.htmlのmember.pkが引き渡される)
def upd(request, member_pk):
    global user_pk
    global pos_y

    #更新対象が自分以外だったら更新しない。エラーメッセージが見えるようにスクロールも先頭へ
    if member_pk != user_pk:
        member = Member.objects.order_by('id')
        return render(request, 'status/index.html', {'member': member, 'error':'!!自分以外のステータスは更新できません!!','position':0})
    
    #更新対象が自分だったら更新。
    else:
        #pk(プライマリーキー)をもとにMemberテーブルから自分データを取得、tにわたす。
        t = Member.objects.get(pk=user_pk)
    
        # workボタンがクリックされた場合の処理
        if 'work' in request.POST:
            if t.status_work:
                t.status_work = 'False'
            else:
                t.status_work = 'True'
    
        # homeボタンがクリックされた場合の処理
        if 'home' in request.POST:
            if t.status_home:
                t.status_home = 'False'
            else:
                t.status_home = 'True'
    
        # meetingボタンがクリックされた場合の処理
        # LITE-90 meetingとlunchの排他制御実装
        if 'meeting' in request.POST:
            if t.status_meeting:
                t.status_meeting = 'False'
            else:
                t.status_meeting = 'True'
                t.status_lunch = 'False'
    
        # lunchボタンがクリックされた場合の処理
        # LITE-90 meetingとlunchの排他制御実装
        if 'lunch' in request.POST:
            if t.status_lunch:
                t.status_lunch = 'False'
            else:
                t.status_lunch = 'True'
                t.status_meeting = 'False'

        # 最終更新時刻を更新
        t.last_update_time = timezone.localtime()

        #save()でDBに反映される。
        t.save()

        # スクロール位置をグローバル変数に渡す
        pos_y = request.POST.get('positionY',0)
    
        return redirect('status:index')

mimamorukun/status/templates/status/index.html
<!DOCTYPE html>
<html>
{% load static %}
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="refresh" content="5" >
    <title>みまもる</title>
    <link href="https://use.fontawesome.com/releases/v5.6.1/css/all.css" rel="stylesheet">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/font-awesome/4.4.0/css/font-awesome.min.css">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css" integrity="sha384-JcKb8q3iqJ61gNV9KGb8thSsNjpSL0n8PARn9HuZOnIxN0hoP+VmmDGMN5t9UJ0Z" crossorigin="anonymous">
    <link rel="stylesheet" href="{% static 'style.css' %}">
    <link rel="icon" type="image/x-icon" href="{% static 'favicon_black.ico' %}">
</head>

<body>
    <div class="container">
        <header>
            <h1>
                <td align="center">みまもる</td>
                <i class="fa fa-coffee"></i>
            </h1>
            <div id="ham-menu">
                <ul>
                    <li>勤怠状況</li>
                    <li><a href="https://coordinated-history-8015.glideapp.io" target="_blank">図書管理アプリ</a></li>
                    <li>メニュー3</li>
                </ul>
            </div>
            <div id="menu-background"></div>
        </header>
    </div>

    <hr>

    <div class="container-fluid">
            <h3>
                <p>Work Status</p>
            </h3>
    </div>
    
    <!-- 自分以外を更新しようとするとエラーメッセージ表示 -->
    {% if error %}
    <hr>
    <h5>
    {{ error }}
    {% endif %}
    </h5>
    <hr>
    <main class="container-fluid">
    {% for member in member.all %}
        <h4>
          <div class="row">
                <p>
                  <div class="my-box col-3">
                    <form action="{% url 'status:update' member.pk %}" method="POST">
                      {% csrf_token %}
                      {% if member.status_work %}
                        <button type="submit" name="work" class="btn"><i class="fas fa-user-circle fa-2x"></i></button>
                      {% else %}
                        <button type="submit" name="work" class="btn"><i class="fas fa-user-circle fa-2x icon-gray"></i></button>
                      {% endif %}
                        <input type="hidden" id="positionY" name="positionY" value={{ position }}>
                    </form>
                  </div>
                  <div class="my-box col-2">
                    <h5 class="name">{{ member.name }}</h5>
                  </div>
                  <div class="my-box col-7">
                    <div class="index">
                      <form action="{% url 'status:update' member.pk %}" method="POST">
                        {% csrf_token %}
                        {% if member.status_home %}
                          <button type="submit" name="home" class="btn" style="width:30px; height:30px"><i class="fas fa-home"></i></button>
                        {% else %}
                          <button type="submit" name="home" class="btn" style="width:30px; height:30px"><i class="fas fa-home icon-gray"></i></button>
                        {% endif %}
                          <input type="hidden" id="positionY" name="positionY" value={{ position }}>
                      </form>
                      <form action="{% url 'status:update' member.pk %}" method="POST">
                        {% csrf_token %}
                        {% if member.status_meeting %}
                          <button type="submit" name="meeting" class="btn" style="width:30px; height:30px"><i class="fas fa-users"></i></button>
                        {% else %}
                          <button type="submit" name="meeting" class="btn" style="width:30px; height:30px"><i class="fas fa-users icon-gray"></i></button>
                        {% endif %}
                          <input type="hidden" id="positionY" name="positionY" value={{ position }}>
                      </form>
                      <form action="{% url 'status:update' member.pk %}" method="POST">
                        {% csrf_token %}
                        {% if member.status_lunch %}
                          <button type="submit" name="lunch" class="btn" style="width:30px; height:30px"><i class="fas fa-utensils"></i></button>
                        {% else %}
                          <button type="submit" name="lunch" class="btn" style="width:30px; height:30px"><i class="fas fa-utensils icon-gray"></i></button>
                        {% endif %}
                          <input type="hidden" id="positionY" name="positionY" value={{ position }}>
                      </form>
                    </div>
                  </div>                
                </p>
          </div>
            <div class="row">           
              <p>
                <div class="my-box col-11 align-right">
                  <h6>
                      <p align="right">最終更新時刻 :<class="last_update_time">{{ member.last_update_time }}</p>
                  </h6>
                </div>
              </p>
            </div> 
        </h4>
    {% endfor %}
    </main>

    <hr>

    <div class="container">
        <footer>
            <p>&copy; MUIT</p>
        </footer>
    </div>
    <!-- Optional JavaScript -->
    <!-- jQuery first, then Popper.js, then Bootstrap JS -->
    <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.1/dist/umd/popper.min.js" integrity="sha384-9/reFTGAW83EW2RDu2S0VKaIzap3H66lZH81PoYlFhbGU+6BZp6G7niu735Sk7lN" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js" integrity="sha384-B4gt1jrGC7Jh4AgTPSdUtOBvfO8shuf57BaghqFfPlYxofvL8/KUEfYiJOMMV+rV" crossorigin="anonymous"></script>
<!-- リロード時のスクロール位置保持のスクリプト -->
<script>
function hoge() {
          var re = /&page_x=(\d+)&page_y=(\d+)/;
          var page_x = document.documentElement ? document.documentElement.scrollLeft : document.body.scrollLeft;
          var page_y = document.documentElement ? document.documentElement.scrollTop : document.body.scrollTop;
          var position = '&page_x=' + page_x + '&page_y=' + page_y;
          if(!url.match(re)) {
                  //初回
                  location.href = url + position;
          } else {
                  //2回目以降
                  location.href = url.replace(/&page_x=(\d+)&page_y=(\d+)/,position);
          }
}
window.onscroll = function(){
          var page_y = document.documentElement ? document.documentElement.scrollTop : document.body.scrollTop;
//          document.getElementsByName("positionY")[0].value = page_y;
//          document.getElementsByName("positionY")[3].value = page_y;
          var elements = document.getElementsByName("positionY");
          for(var i = 0; i < elements.length; ++i){
              elements[i].value = page_y;
          }

}

// スクロール位置を復元
function restore_scroll() {
        var re = /&page_x=(\d+)&page_y=(\d+)/;
        if(window.location.href.match(re)) {
                var position = window.location.href.match(re)
                window.scrollTo(position[1],position[2]);
        }else{
            var position = document.getElementsByName("positionY")[0].value;
            window.scrollTo(0, position);
        }
}

(window.onload = function() {
        restore_scroll();
})();

// Andoroidで拡大できないようにするおまじない
document.querySelector("[name=viewport]").setAttribute("content", "width=device-width, initial-scale=1, user-scalable=no");

</script>

</body>
</html>

mimamorukun/status/templates/status/login.html
<!doctype html>
<html>
  {% load static %}
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css" integrity="sha384-JcKb8q3iqJ61gNV9KGb8thSsNjpSL0n8PARn9HuZOnIxN0hoP+VmmDGMN5t9UJ0Z" crossorigin="anonymous">
    <link rel="icon" type="image/x-icon" href="{% static 'favicon_black.ico' %}">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/font-awesome/4.4.0/css/font-awesome.min.css">
    <link href="https://use.fontawesome.com/releases/v5.6.1/css/all.css" rel="stylesheet">
    
    <title>ログイン画面</title>
    
  </head>
    
  <body style="background-color:#e9eff4; margin-top:150px;">
  
    <form class="form-signin" method="POST" action='' align="center">{% csrf_token %}
    
      <!--　マグカップアイコン -->
      <i class="fas fa-coffee fa-5x" style="margin-bottom:20px"></i>

      <h1 class="h3 mb-3 font-weight-normal">Please login</h1>
      
      <!--　登録されてない名前の場合、エラーメッセージ表示 -->
      {% if error %}
        {{ error }}
      {% endif %}
      
      <div align="center"> 
        <input type="text" id="inputname" class="form-control" name="username" placeholder="username(苗字)" style="width:300px; margin-top:10px;" required autofocus>
        <button class="btn btn-lg btn-primary" type="submit" style="width:300px; margin-top:10px;">login</button>
        <br>
        <p class="mt-5 mb-3 text-muted">&copy; MUIT</p>
　　　　　</div>

    </form>
    

    <!-- Optional JavaScript -->
    <!-- jQuery first, then Popper.js, then Bootstrap JS -->
    <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.1/dist/umd/popper.min.js" integrity="sha384-9/reFTGAW83EW2RDu2S0VKaIzap3H66lZH81PoYlFhbGU+6BZp6G7niu735Sk7lN" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js" integrity="sha384-B4gt1jrGC7Jh4AgTPSdUtOBvfO8shuf57BaghqFfPlYxofvL8/KUEfYiJOMMV+rV" crossorigin="anonymous"></script>
  </body>
</html>